version: '3'

services:

  tomcat-proxy:
    build: .
    volumes:
      - ./src:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    environment:
      APP_NAME: 'helloservlet'
      APP_CLASS: 'mypkg'      
      KEYCLOAK_URL: "localhost:8180/auth"      
      SECRET: 3c5a7f7a-f4c5-4b4e-92a3-0fcc3a734dc6
      AZ_CLIENT_TRUST_STORE_FILE: /usr/local/tomcat/truststore-client.p12
      AZ_CLIENT_TRUST_STORE_TYPE: PKCS12
      AZ_CLIENT_TRUST_STORE_PASSWORD: asclepios
      AZ_SERVER_ENDPOINTS: https://pdp-server:7071/checkJsonAccessRequest
      AZ_SERVER_ACCESS_KEY: 7235687126587231675321756752657236156321765723
      AZ_CALL_DISABLED: "false"
      AZ_CALL_LOAD_BALANCE_METHOD: ORDER
      AZ_CALL_RETRIES: 1
    volumes:
      - truststore-client.p12:/usr/local/tomcat/truststore-client.p12
    command: [ "run.sh" ]

  pdp-server:
    image: registry.gitlab.com/asclepios-project/abac-authorization/abac-server:latest
    volumes:
      - abac_conf:/abac-server/config
      - abac_policies:/abac-server/policies
      - abac_logs:/abac-server/logs    
    ports:
      - "7071:7071"
    expose:
      - "7071"

  #ample-editor:
    #image: registry.gitlab.com/asclepios-project/ample-editor
    #volumes:
      #- ample_conf:/ample/conf
      #- ample_DB:/ample/DB
      #- ample_logs:/ample/logs
#    environment:
#      - ABAC_SERVER_HOST=${ABAC_SERVER_HOST}
#      - ABAC_SERVER_API_KEY=${ABAC_SERVER_API_KEY}    
    #ports:
    #  - "9090:9090"
    #expose:
      #- "9090"

  #keycloak:
    #image: jboss/keycloak:9.0.2
    #environment:
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_HOSTNAME: "192.168.2.5"
      #PROXY_ADDRESS_FORWARDING: "true"
    #ports:
      #- "8180:8080"
    #expose:
      #- "8180"

  web1:
    build: ./django-application/
    environment:
      #KEYCLOAK_URL: "localhost:8180/auth"      
      SECRET: 3c5a7f7a-f4c5-4b4e-92a3-0fcc3a734dc6

    expose:
      - "8000"

volumes:
  abac_conf:
  abac_policies:
  abac_logs:
  ample_conf:
  ample_DB:
  ample_logs:
